apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-3
  template:
    metadata:
      labels:
        app: task-3
    spec:
      containers:
      - name: task-3
        image: nginx:alpine
        ports:
        - containerPort: 80